#!/bin/bash

# A script to help manage the openSUSE:Tumbleweed project
# (C) 2010 Greg Kroah-Hartman <gregkh@suse.de>
# Released under the GPL v2.
#
# This script reads the file 'package_list' and runs 'check_package'
# on all of the packages listed in it.
#
# Any questions/comments/patches are gladly welcome, just send to:
#	Greg Kroah-Hartman <gregkh@suse.de>
#

while read line
do
	# remove lines that start with a # and all whitespace in the line
	line=`echo $line | sed -e '/^#/d' | sed -e 's/^[ \t]*//;s/[ \t]*$//'`
	if [ "$line" != "" ]
	then
		./check_package $line
	fi
done < package_list

