#!/bin/bash

# A script to help manage the openSUSE:Tumbleweed project
# (C) 2010 Greg Kroah-Hartman <gregkh@suse.de>
# Released under the GPL v2.
#
# This script checks the links that are set up for a single Tumbleweed package.
# Tumbleweed works either by having packages submitted to it, or by linking to
# a "known stable" repository in the build service.  This script checks the
# repo and package name requested on the command line and verifies that they
# are up to date.  If they are not up to date, the proper 'osc' command is
# printed to output to be run by hand if necessary.
#
# If the package is not in the Tumbleweed repo, the proper 'osc' command
# to add it is printed out if you wish to run it.
#
# Any questions/comments/patches are gladly welcome, just send to:
#	Greg Kroah-Hartman <gregkh@suse.de>
#

# Main Tumbleweed repository location
TUMBLE_REPO="openSUSE:Tumbleweed"


# expects:
#	$PACKAGE to be set to the package name to be checked
#	$REPO to be set to the base repo name
compare_version() {

	EXISTING=`osc cat $TUMBLE_REPO/$PACKAGE/_link 2> /dev/null | grep rev | cut -f 4 -d ' ' | cut -f 2 -d '=' | cut -f 1 -d '=' | sed -e 's/\"//g'`
	#echo $EXISTING

	NEW=`osc log --csv $REPO/$PACKAGE 2> /dev/null | head -n 1 | cut -f 4 -d '|'`
	#echo $NEW

	if [ "$EXISTING" = "" ]
	then
		echo "# $PACKAGE is not in Tumbleweed, add it by doing:"
	fi

	if [ "$NEW" = "$EXISTING" ]
	then
		echo "# $PACKAGE is up to date."
	else
		echo "osc linkpac -f -r $NEW $REPO $PACKAGE $TUMBLE_REPO"
	fi
}

if [ $# -ne 1 ]; then
	echo -e "Usage:\t $0 repo/packagename\ne.g.\t $0 Kernel:stable/kernel-source"
	exit 1
fi


FULL_PACKAGE=$1

# I'm sure that bash regex can do this better, but hey, this works...
REPO=`echo $FULL_PACKAGE | cut -f 1 -d '/'`
PACKAGE=`echo $FULL_PACKAGE | cut -f 2 -d '/'`
#echo $REPO
#echo $PACKAGE

compare_version
