#!/usr/bin/perl

#my $repository = "openSUSE:Tumbleweed:KDE";
my $repository = "openSUSE:Tumbleweed:Testing";
#my $repository = "openSUSE:Tumbleweed";

my %kde_sub_packages = (
	"kdelibs4-apidocs" => "kdelibs4",
	"libqt4-sql-plugins" => "libqt4",
	"libqt4-devel-doc" => "libqt4",
	"soprano-backend-sesame" => "soprano",
	"soprano-backend-virtuoso" => "soprano"
);

foreach $sub_package (sort keys %kde_sub_packages){
	#system("osc rdelete $repository $sub_package");
	printf("osc linkpac -C copy $repository $kde_sub_packages{$sub_package} $repository $sub_package\n");
	#system("osc linkpac -C copy $repository $kde_sub_packages{$sub_package} $repository $sub_package");
}
